#cloud-config
package_update: true
package_upgrade: true

packages:
  - redis-server

runcmd:
  - sed -i 's/^bind 127.0.0.1.*/bind 0.0.0.0/' /etc/redis/redis.conf
  - sed -i 's/^protected-mode yes/protected-mode no/' /etc/redis/redis.conf
  - systemctl enable --now redis-server
